# download file from "https://github.com/jc141x/releases-feed/releases/download/feeds/releases.json" and push it to main branch every 5 minutes
name: Push releases.json
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download releases.json
      # download file from "https://github.com/jc141x/releases-feed/releases/download/feeds/releases.json"
        run: wget "https://github.com/jc141x/releases-feed/releases/download/feeds/releases.json" -O releases.json

